// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjJ6ZsuCIqiHoEu24l_hXo5uFaeEpb4aU',
    appId: '1:217590541556:web:5c01156c0dd9cbdda342a1',
    messagingSenderId: '217590541556',
    projectId: 'renta-control',
    authDomain: 'renta-control.firebaseapp.com',
    storageBucket: 'renta-control.firebasestorage.app',
    measurementId: 'G-ZFQWRSYZ51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxpbWmHjBzkhVtOTEKAAgz-E76VOg8kE8',
    appId: '1:217590541556:android:f57076744f605800a342a1',
    messagingSenderId: '217590541556',
    projectId: 'renta-control',
    storageBucket: 'renta-control.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQqiIicUqQfkGnDqCuXP6Gb4sqp0N8ASE',
    appId: '1:217590541556:ios:b319aa3f46eaf406a342a1',
    messagingSenderId: '217590541556',
    projectId: 'renta-control',
    storageBucket: 'renta-control.firebasestorage.app',
    iosBundleId: 'com.example.rentaControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQqiIicUqQfkGnDqCuXP6Gb4sqp0N8ASE',
    appId: '1:217590541556:ios:b319aa3f46eaf406a342a1',
    messagingSenderId: '217590541556',
    projectId: 'renta-control',
    storageBucket: 'renta-control.firebasestorage.app',
    iosBundleId: 'com.example.rentaControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjJ6ZsuCIqiHoEu24l_hXo5uFaeEpb4aU',
    appId: '1:217590541556:web:f9bbc5f45d7282dca342a1',
    messagingSenderId: '217590541556',
    projectId: 'renta-control',
    authDomain: 'renta-control.firebaseapp.com',
    storageBucket: 'renta-control.firebasestorage.app',
    measurementId: 'G-ZL69H9LY31',
  );

}